version: '3.7'
services:
  database:
    image: postgres:11
    volumes:
      - database_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: dockernuxeo
      POSTGRES_USER: dockernuxeo
      POSTGRES_DB: nuxeo
  nuxeo:
    build: .docker
    image: pburkholder/nuxeo
    ports:
      - 8080:8080
    volumes:
      - nuxeo_data:/var/lib/nuxeo/data:delegated
    environment:
       NUXEO_DB_TYPE: postgresql
       NUXEO_CLID: "49ef6ec4-31ba-4176-a88f-ed506cff1f82.1559432297.DpSC3DPdcDiQ/FR8y08AlkN1S6XFnkwpO35RF6TYGXlOLZL/QXF8RUwgYel2Bjqr5u8EJ/kNom2UzMpMAp61RPmAEEFgtYvumuDCc3EL6Ddbnu+mn3tfdX9zE9NWJVio6WDGnxAu4QU0yExk8IYgy7usN7x3NQ56OXo1dfOJ24uGmnqW1nWKuYlQFd8dta3wkK/cKqlpQutfwY4nC9KsYldzO/kVSGLdCVY5+TfrHDGeDmNpewmc8o78MGOwrj2Ofm5yxzRFjHJ5rUFSIxgb1TkUj2DkXtRML3yAGvBl4gMoL2ifVrpGYJ3gvkvqCosk8adWhGVSNAzyKrZn0GtadA==--3cbe013c-8daf-4744-bdc6-64eb1cc1b066"
       NUXEO_PACKAGES: "nuxeo-dam nuxeo-web-ui nuxeo-platform-getting-started amazon-s3-online-storage"
       VCAP_SERVICES: >
        { "aws-rds": [{
            "name": "database",
            "credentials": {
              "db_name": "nuxeo",
              "host": "database",
              "password": "dockernuxeo",
              "port": "3306",
              "username": "dockernuxeo"
            }
          }]
        }
    depends_on:
      - database
      - storage
      - bucketmaker
#       NUXEO_DB_HOST: database
#      # 
#      CF_INSTANCE_INDEX: '0'
#      VCAP_APPLICATION: >
#        {"name": "web"}
#          "user-provided": [{
#            "name": "secrets",
#            "credentials": {
#              "ADMIN_EMAIL": "secret@example.com",
#              "CRON_KEY": "SECRET",
#              "HASH_SALT": "SECRET",
#              "ROOT_USER_NAME": "root",
#              "ROOT_USER_PASS": "root"
#            }
#          }],
#          "s3": [{
#            "name": "storage",
#            "s3fake": "true",
#            "credentials": {
#              "access_key_id": "ACCESS_KEY_ID",
#              "bucket": "cgbucket",
#              "region": "us-west-1",
#              "secret_access_key": "secret123",
#              "uri": "s3://ACCESS_KEY_ID:secret123@storage/cgbucket"
#            },
#            "label": "s3",
#            "plan": "basic-public"
#           }]
#        }
  storage:
    restart: always
    networks:
      default:
        aliases:
          - cgbucket.s3-us-west-1.amazonaws.com
          - s3-us-west-1.amazonaws.com
    image: minio/minio:latest
    environment:
      MINIO_DOMAIN: "s3-us-west-1.amazonaws.com"
      MINIO_ACCESS_KEY: ACCESS_KEY_ID
      MINIO_SECRET_KEY: secret123
    command: minio server --address 0.0.0.0:80 /var/data/fakes3
    volumes:
      - storage_data:/var/data/fakes3:delegated
  bucketmaker:
    image: minio/mc
    environment:
      MINIO_ACCESS_KEY: ACCESS_KEY_ID
      MINIO_SECRET_KEY: secret123
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add storage http://storage ACCESS_KEY_ID secret123;
      /usr/bin/mc mb storage/cgbucket;
      /usr/bin/mc policy download storage/cgbucket/public"
    depends_on:
      - storage
volumes:
  nuxeo_data:
  database_data:
  storage_data:
