version: '3.7'
services:
  database:
    image: postgres:11
    volumes:
      - database_data:/var/lib/postgresql/data:delegated
    environment:
      POSTGRES_PASSWORD: nuxeo
      POSTGRES_USER: nuxeo
#  storage:
#    restart: always
#    networks:
#      default:
#        aliases:
#          - cg-bucket.s3-us-west-1.amazonaws.com
#          - s3-us-west-1.amazonaws.com
#    image: minio/minio:latest
#    environment:
#      MINIO_DOMAIN: "s3-us-west-1.amazonaws.com"
#      MINIO_ACCESS_KEY: ACCESS_KEY_ID
#      MINIO_SECRET_KEY: secret123
#    command: minio server --address 0.0.0.0:80 /var/data/fakes3
#    volumes:
#      - storage_data:/var/data/fakes3:delegated
#  bucketmaker:
#    image: minio/mc
#    environment:
#      MINIO_ACCESS_KEY: ACCESS_KEY_ID
#      MINIO_SECRET_KEY: secret123
#    entrypoint: >
#      /bin/sh -c "
#      /usr/bin/mc config host add storage http://storage ACCESS_KEY_ID secret123;
#      /usr/bin/mc mb storage/cg-bucket;
#      /usr/bin/mc policy download storage/cg-bucket/public"
#    depends_on:
#      - storage
  nuxeo:
#    command: "/var/www/.docker/startup"
    image: pburkholder/nuxeo
    ports:
      - 8080:8080
    volumes:
      - nuxeo_data:/var/lib/nuxeo/data:delegated
    depends_on:
      - database
#      - bucketmaker
    environment:
       NUXEO_DB_TYPE: postgresql
       NUXEO_DB_HOST: database
#      # 
#      NUXEO_PACKAGES: "nuxeo-dam nuxeo-web-ui nuxeo-platform-getting-started"
#      CF_INSTANCE_INDEX: '0'
#      VCAP_APPLICATION: >
#        {"name": "web"}
#      VCAP_SERVICES: >
#        { "aws-rds": [{
#            "name": "database",
#            "credentials": {
#              "db_name": "mysql",
#              "host": "database",
#              "password": "mysql",
#              "port": "3306",
#              "username": "root"
#            }
#          }],
#          "user-provided": [{
#            "name": "secrets",
#            "credentials": {
#              "ADMIN_EMAIL": "secret@example.com",
#              "CRON_KEY": "SECRET",
#              "HASH_SALT": "SECRET",
#              "ROOT_USER_NAME": "root",
#              "ROOT_USER_PASS": "root"
#            }
#          }],
#          "s3": [{
#            "name": "storage",
#            "s3fake": "true",
#            "credentials": {
#              "access_key_id": "ACCESS_KEY_ID",
#              "bucket": "cg-bucket",
#              "region": "us-west-1",
#              "secret_access_key": "secret123",
#              "uri": "s3://ACCESS_KEY_ID:secret123@storage/cg-bucket"
#            },
#            "label": "s3",
#            "plan": "basic-public"
#           }]
#        }
volumes:
  nuxeo_data:
  database_data:
#  storage_data:
